### ISSUE TITLE
Juju-related labels are added to alert rules, but missing from the metrics

### ISSUE THREAD

**Issue by imanenami** [canonical/opentelemetry-collector-operator#78]
### Bug Description

I have noticed that OTelCol is automatically adding juju-related labels (like application, model, etc. ) to the alert rules, but the same labels aren't added to the metrics themselves, causing the alerts never fire.

Am I missing something here?

### To Reproduce

```
# Clone & pack Karapace charm
git clone https://github.com/canonical/karapace-operator && cd karapace-operator
git checkout o11y
charmcraft pack
juju deploy ./karapace_ubuntu@24.04-amd64.charm

# Clone & build OTelCol
git clone git@github.com:canonical/opentelemetry-collector-operator.git && cd opentelemetry-collector-operator
charmcraft pack
juju deploy ./opentelemetry-collector_ubuntu@24.04-amd64.charm otelcol

# integrations
juju deploy kafka --channel 4/edge --config roles="broker,controller"
juju integrate kafka karapace
juju integrate karapace otelcol

# assuming you've consumed COS offers
juju integrate otelcol prometheus-receive-remote-write
juju integrate otelcol loki-logging
juju integrate otelcol grafana-dashboards



### Environment

Running on lxd 5.21.3 LTS, juju 3.6.8


### Relevant log output

```shell
---
```

### Additional context

Alerts:

<img width="1750" height="318" alt="Image" src="https://github.com/user-attachments/assets/d2a4dd93-2a67-47ed-9a53-a76f9ed8e1d4" />

Metrics:

<img width="1750" height="318" alt="Image" src="https://github.com/user-attachments/assets/4110e99e-cf1c-4da0-80b7-5f38dfbd6a86" />

**Comment by Abuelodelanada** [comment]
Hi @imanenami 

I deployed this but I could not reproduce the issue:

```shell
Model  Controller  Cloud/Region         Version  SLA          Timestamp
apps   lxd         localhost/localhost  3.6.8    unsupported  10:52:52-03:00

SAAS                             Status  Store     URL
grafana-dashboards               active  microk8s  admin/cos.grafana-dashboards
loki-logging                     active  microk8s  admin/cos.loki-logging
prometheus-receive-remote-write  active  microk8s  admin/cos.prometheus-receive-remote-write

App       Version          Status  Scale  Charm                    Channel  Rev  Exposed  Message
kafka     4.0.0            active      1  kafka                    4/edge   228  no       
karapace  5.0.1.dev0+g...  active      1  karapace                            0  no       
otelcol                    active      1  opentelemetry-collector             9  no       

Unit           Workload  Agent  Machine  Public address  Ports                Message
kafka/0*       active    idle   5        10.200.147.149  9092,9098,19093/tcp  
karapace/0*    active    idle   4        10.200.147.146                       
  otelcol/12*  active    idle            10.200.147.146                       

Machine  State    Address         Inst id        Base          AZ  Message
4        started  10.200.147.146  juju-d937cc-4  ubuntu@24.04      Running
5        started  10.200.147.149  juju-d937cc-5  ubuntu@24.04      Running

Integration provider                                  Requirer                   Interface                Type         Message
kafka:cluster                                         kafka:cluster              cluster                  peer         
kafka:kafka-client                                    karapace:kafka             kafka_client             regular      
kafka:refresh-v-three                                 kafka:refresh-v-three      refresh-v-three          peer         
kafka:restart                                         kafka:restart              rolling_op               peer         
karapace:cluster                                      karapace:cluster           cluster                  peer         
karapace:cos-agent                                    otelcol:cos-agent          cos_agent                subordinate  
karapace:restart                                      karapace:restart           rolling_op               peer         
otelcol:peers                                         otelcol:peers              otelcol_replica          peer         
prometheus-receive-remote-write:receive-remote-write  otelcol:send-remote-write  prometheus_remote_write  regula
```

I see no karapace metric in Promethues.

Please, may you share the otelcol config file? It is in: `/etc/otelcol/config.d/otelcol_NN.yaml`

In my otelcol config file I see:


```yaml
  prometheus/cos-agent/otelcol/12:
    config:
      scrape_configs:
      - job_name: karapace_0_default
        metrics_path: /metrics
        scrape_interval: 1m
        scrape_timeout: 10s
        static_configs:
        - labels:
            juju_application: karapace
            juju_model: apps
            juju_model_uuid: 335a2de5-726e-4ef2-83d4-b29584d937cc
            juju_unit: karapace/0
          targets:
          - localhost:4317
      - job_name: karapace_1_default
        metrics_path: /metrics
        scrape_interval: 1m
        scrape_timeout: 10s
        static_configs:
        - labels:
            juju_application: karapace
            juju_model: apps
            juju_model_uuid: 335a2de5-726e-4ef2-83d4-b29584d937cc
            juju_unit: karapace/0
          targets:
          - localhost:9125
```

This section has issues:

1. Port `4317` is not a valid `kadrapace` port, is instead the `grpc` port used by otelcol's `otlp`, you can see this in the config file:

```yaml
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
```

2. Port `9125` is not working:

```shell
$ curl -m 10 localhost:9125/metrics
curl: (28) Operation timed out after 10002 milliseconds with 0 bytes received
```

**Comment by imanenami** [comment]
I don't think so, the metrics are exposed without authentication, and they're being sent to prometheus, but the juju labels are missing for some reason...

**Comment by imanenami** [comment]
Update: I think the issue is that OtelCol only adds labels to prometheus exporters, but not otlp ones. The solution IMHO could be adding a processor which adds the required juju-related attributes

**Comment by imanenami** [comment]
@MichaelThamm and @Abuelodelanada you're right about the prometheus exporter ports, so the right config would be:

```python
        self._grafana_agent = COSAgentProvider(
            self,
            metrics_endpoints=[
                {"path": "/metrics", "port": 9102},
            ],
            refresh_events=[self.on.update_status, self.on.upgrade_charm],
            # snip ...
        )
```

But still, the issue persists because OTelCol does not add the required labels to the metrics sent to the `otlp` collector. As I mentioned earlier, I think a processor should be added for such metrics...

**Comment by MichaelThamm** [comment]
Can you send the outputs of:
1. `juju status --relations`
2. `juju ssh karapace/0 "sudo cat /var/snap/charmed-karapace/current/etc/karapace/karapace.config.json"`

**Comment by MichaelThamm** [comment]
1. "karapace 5 ONLY supports OTLP GRPC endpoints"
	- I assume you are referring to the `karapace.config.json` config. However, our `COSAgentProvider` gathers the endpoints you define and adds them as scrape jobs to be scraped by the otelcol `prometheus` receiver for ingestion into otelcol. This means that it does not matter what Karapace "supports".

2. "we won't have our metrics of interest": `9102/metrics`, `80801/metrics`
	- This is concerning and would mean `COSAgentProvider`'s `metrics_endpoints` argument is useless because these scrape jobs would not be scrapable:

```python
self._grafana_agent = COSAgentProvider(
    self,
    metrics_endpoints=[
        {"path": "/metrics", "port": 9102},
        {"path": "/metrics", "port": 8081},
    ],
    refresh_events=[self.on.update_status, self.on.upgrade_charm],
    # snip ...
)
```

3. "o11y team doesn't have any plans to add support for adding juju topology labels to OTLP metrics?"
	- We do support adding juju topology labels to ANY metrics which are scraped via `COSAgentProvider`.
		- Only the receiver (and port) care what format the metrics are, so when you say "OTLP metrics" these metrics look exactly like any other metrics once in otelcol.
	- The problem is that you are trying to "export" these metrics to otelcol via Karapace natively and Karapace has no support for injecting Juju topology labels.
